site_name: Data consistency in context of Kafka and Event Streams
base_url: /
repo_url: https://github.com/ibm-cloud-architecture/refarch-eda-data-consistency.git
nav:
  - Introduction: index.md
  - Compendium: compendium.md
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences