apiVersion: eventstreams.ibm.com/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: mm2
  namespace: integration
spec:
  template:
    pod:
      metadata:
        annotations:
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: 10.0.0
          productMetric: VIRTUAL_PROCESSOR_CORE
          productChargedContainers: mm2-mirrormaker2
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          cloudpakVersion: 2020.2.1
          productCloudpakRatio: '2:1'
  version: 2.5.0
  replicas: 1
  connectCluster: "event-streams-wdc"
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  clusters:
  - alias: "es-1"
    bootstrapServers: es-1-kafka-bootstrap.integration.svc:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      ssl.endpoint.identification.algorithm: https
    tls: 
      trustedCertificates:
        - secretName: es-1-cluster-ca-cert
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        certificate: user.crt
        key: user.key
        secretName: mm2
  - alias: "event-streams-wdc"
    bootstrapServers: broker-0-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-1-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-2-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-3-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-4-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-5-qnprtqnp7hnkssdz.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
    tls: {}
    authentication:
      passwordSecret:
          secretName: es-oc-api-secret  
          password: password 
      username: token
      type: plain
  mirrors:
  - sourceCluster: "es-1"
    targetCluster: "event-streams-wdc"
    sourceConnector:
      config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
          heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
          checkpoints.topic.replication.factor: 1
    topicsPattern: products
